version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/yuyanzhe
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 